### ISSUE TITLE
28C64 Not Working

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [TomNisbet/TommyPROM#38]

**Comment by TomNisbet** [comment]
You're gonna have to give me a little more info!

**Comment by ElectroBoy404NotFound** [comment]
> You're gonna have to give me a little more info!

Nvm it is working ig, i connected OE wrong

**Comment by ElectroBoy404NotFound** [comment]
i will test it

**Comment by ElectroBoy404NotFound** [comment]
Not working

**Comment by ElectroBoy404NotFound** [comment]
Im using ben eater's programmer with 2 extra lines connected to the 2 more lines on EEPROM, i also tried to change the code to unlock the EEPROM using the diagram they gave in the data sheet

**Comment by ElectroBoy404NotFound** [comment]
@TomNisbet
