### ISSUE TITLE
Hardware Verify Not Working?

### ISSUE THREAD

**Issue by OrlandoBlyat** [TomNisbet/TommyPROM#54]
Hi,
I've assembled the TommyPROM on a breadboard with the 74HCT595 registers. But writing/reading aren't functioning properly, my wiring probably is at fault. I uploaded the HardwareVerify sketch, but in my serial terminal (MobaXTerm) I don't have a CLI (I set the baud rate to 115200). I recieve two '#' and that is it. The standard TommyPROM sketch works as inteded. Screenshots present. 
![image](https://user-images.githubusercontent.com/111756888/230723276-c209ff71-aa3e-4063-9668-4786b4137e32.png)
/Terminal with the Hardware Verify Sketch/

![image](https://user-images.githubusercontent.com/111756888/230723401-17e81cf7-ec9c-4589-8802-c295bde684be.png)
/Terminal with the TommyPROM sketch/

**Comment by TomNisbet** [comment]
The verify sketch doesn't print any header to identify itself, just the # character for the prompt.  Did you try entering any commends?  It uses the same terminal ode as TommyPROM, so if you were able to use one, then the other should work as well.

What kind of chip are you programming?  Can you try the Z command in TommyPROM and post the results?  Do Z0 and then D0.

**Comment by OrlandoBlyat** [comment]
Hello,
sorry for the late response, I guess GitHub didn't send me an email about the response.
As I said, the terminal is exhibiting kind of strange behavior:
![image](https://user-images.githubusercontent.com/111756888/232587483-fadd40ee-2abc-4827-bce3-eb85cea71785.png)
----
![image](https://user-images.githubusercontent.com/111756888/232587569-a0e76005-b848-43fc-a56a-7cef71e92a48.png)
----
I can input the command, pressing enter returns the cursor to line start. None of the commands return anything.
![image](https://user-images.githubusercontent.com/111756888/232587784-987df44a-927a-42f0-b4a4-8955d94c366f.png)
----
I've also tried using TeraTermYT but it doesn't change.

![image](https://user-images.githubusercontent.com/111756888/232588556-d3d8a68f-2a79-481f-b218-335db0cc699c.png)

**Comment by SvenPaterson** [comment]
I too seem to have had this exact same issue using teraterm. Worked just fine in the arduino native serial monitor once I finally tried using it!
