### ISSUE TITLE
TommyPROM32 : Ok to replace SW1 and SW2 with jumpers ?

### ISSUE THREAD

**Issue by ABelliqueux** [TomNisbet/TommyPROM#72]
As switches with the correct size/footprint  are hard to source at a decent price where I am, and only one of the position is used, is it okay to replace them with a jumper like so ? 

![2024-06-15-181232_694x782_scrot](https://github.com/TomNisbet/TommyPROM/assets/1405255/18c82360-f6f9-4df2-bdf2-7e330f1a8a0a)

![2024-06-15-181254_665x787_scrot](https://github.com/TomNisbet/TommyPROM/assets/1405255/d39f722a-a443-4c99-b033-3ad3541b1ccb)

![2024-06-15-181550_599x507_scrot](https://github.com/TomNisbet/TommyPROM/assets/1405255/7cf1f6e5-66ea-4432-b343-8f83ce43eef7)

**Comment by TomNisbet** [comment]
Yes, that should work just fine.

**Comment by ABelliqueux** [comment]
Cool, thanks !
